version: '3.9'
services:
  server:
    build:
      context: .
      target: development
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@database:5432/database
      - GRAPHQL_SANDBOX=${GRAPHQL_SANDBOX}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_CREDENTIALS_CLIENT_ID=${GCP_CREDENTIALS_CLIENT_ID}
      - GCP_CREDENTIALS_CLIENT_EMAIL=${GCP_CREDENTIALS_CLIENT_EMAIL}
      - GCP_CREDENTIALS_PRIVATE_KEY=${GCP_CREDENTIALS_PRIVATE_KEY}
      - GCP_CREDENTIALS_TYPE=${GCP_CREDENTIALS_TYPE}
      - GCP_STORAGE_BUCKET_NAME=${GCP_STORAGE_BUCKET_NAME}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CREDENTIALS_CLIENT_EMAIL=${FIREBASE_CREDENTIALS_CLIENT_EMAIL}
      - FIREBASE_CREDENTIALS_PRIVATE_KEY=${FIREBASE_CREDENTIALS_PRIVATE_KEY}
      - FIREBASE_CLIENT_API_KEY=${FIREBASE_CLIENT_API_KEY}
      - FIREBASE_CLIENT_AUTH_DOMAIN=${FIREBASE_CLIENT_AUTH_DOMAIN}
      - FIREBASE_CLIENT_STORAGE_BUCKET=${FIREBASE_CLIENT_STORAGE_BUCKET}
      - FIREBASE_CLIENT_MESSAGING_SENDER_ID=${FIREBASE_CLIENT_MESSAGING_SENDER_ID}
      - FIREBASE_CLIENT_APP_ID=${FIREBASE_CLIENT_APP_ID}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_SANDBOX=${BREVO_SANDBOX}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d database -h localhost -p 5432']
      interval: 10s
      retries: 5
      timeout: 5s

  migrate:
    build:
      context: .
      target: migration
    volumes:
      - ./src/repositories/database/migrations:/app/src/repositories/database/migrations
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/database
    depends_on:
      database:
        condition: service_healthy

volumes:
  database:
